- name: variables from files
  hosts: localhost
  vars_files:
    - variables.yaml
  task:
    - name: print variables 
      ansible.builtin.debug:
        msg: "my name is {{name}}, and my age is {{age}}"
